FROM python:3.13-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ /app/src/
COPY config.py /app/config.py
COPY app.py /app/app.py 
ENV PYTHONPATH=/app

EXPOSE 8000

CMD ["python", "/app/app.py"]

