# Dockerfile.sentiment

FROM python:3.13-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY src/ /app/src/
ENV PYTHONPATH=/app
WORKDIR /app/src/infrastructure/grpc

EXPOSE 50051
CMD ["python", "sentiment_server.py"]
